export enum Estadoscielo {

    NUBES_ALTAS = 17,
    POCO_NUBOSO = 12,
    DESPEJADO = 11,
    MUY_NUBOSO_CON_LLUVIA= 25,
    CUBIERTO_CON_LLUVIA = 26,
    MUY_NUBOSO_CON_LLUVIA_ESCASA= 45,
    INTERVALOS_NUBOSOS_CON_LLUVIA=23,
    MUY_NUBOSO=15,
    NUBOSO=14,
    INTERVALOS_NUBOSOS_CON_LLUVIA_ESCASA=43,
    INTERVALOS_NUBOSOS=13,   
}
